import type { Result, Workout } from "@/lib/api";
import type { DisplayUnits } from "@/lib/units";

export const MOCK_UNITS: DisplayUnits = { weight: "kg", distance: "km" };

function result(over: Partial<Result>): Result {
  return {
    id: crypto.randomUUID(),
    user_id: "u1",
    workout_id: "w1",
    movement_id: null,
    movement_name: "Movement",
    result_type: "weight",
    load_kg: null,
    reps: null,
    time_s: null,
    distance_m: null,
    calories: null,
    height_cm: null,
    rounds: null,
    partial_reps: null,
    watts: null,
    pace_s: null,
    pace_distance_m: 500,
    set_index: 0,
    order_index: 0,
    is_pr: false,
    notes: null,
    variant_annotation: null,
    implement: null,
    tempo: null,
    side: null,
    rpe: null,
    rpe_target: null,
    rir: null,
    rest_s: null,
    mean_velocity_ms: null,
    peak_velocity_ms: null,
    estimated_1rm_kg: null,
    scaled: false,
    created_at: "2026-07-19T06:00:00Z",
    updated_at: "2026-07-19T06:00:00Z",
    ...over,
  };
}

export const MOCK_WORKOUT: Workout = {
  id: "11111111-1111-1111-1111-111111111111",
  user_id: "u1",
  performed_at: "2026-07-19T06:15:00",
  title: "Heavy Pull Day",
  short_hash: "b2c3d4e5",
  notes: "Felt strong on the second set.",
  bodyweight_kg: "82.5",
  session_type: "strength",
  workout_format: "strength",
  time_cap_s: null,
  location: "Home garage",
  session_rpe: "8.0",
  duration_s: 3600,
  perceived_load_au: 480,
  volume_load_kg: "4120.0",
  avg_hr: null,
  max_hr: null,
  trimp_au: null,
  is_tag: false,
  created_at: "2026-07-19T07:20:00Z",
  updated_at: "2026-07-19T07:20:00Z",
  results: [
    result({
      movement_id: "m-deadlift",
      movement_name: "Deadlift",
      implement: "Barbell",
      result_type: "weight",
      load_kg: "180",
      reps: 3,
      estimated_1rm_kg: "198.0",
      rpe: "9",
      order_index: 0,
    }),
    result({
      movement_id: "m-deadlift",
      movement_name: "Deadlift",
      implement: "Barbell",
      result_type: "weight",
      load_kg: "170",
      reps: 5,
      estimated_1rm_kg: "198.3",
      order_index: 1,
    }),
    result({
      movement_id: "m-pullup",
      movement_name: "Weighted Pull-up",
      result_type: "weight",
      load_kg: "25",
      reps: 8,
      scaled: true,
      order_index: 2,
    }),
    result({
      movement_id: "m-row",
      movement_name: "Row",
      result_type: "distance",
      distance_m: "2000",
      order_index: 3,
    }),
  ],
};
