"use client";

import { summarizeAdaptationMagnitude } from "@/lib/adaptationDiff";
import type { AdaptationOut } from "@/lib/api/plans";

const TRIGGER_LABELS: Record<string, string> = {
  high_acwr: "High ACWR",
  low_readiness: "Low Readiness",
  missed_session: "Missed Sessions",
  rpe_creep: "RPE Creep",
};

function triggerChipLabel(adaptation: AdaptationOut): string {
  const base =
    TRIGGER_LABELS[adaptation.trigger_type] ?? adaptation.trigger_type;
  const data = adaptation.trigger_data;
  if (typeof data?.acwr === "number")
    return `${base} · ${data.acwr.toFixed(2)}`;
  if (typeof data?.streak_days === "number")
    return `${base} · ${data.streak_days}d`;
  if (typeof data?.avg_rpe === "number")
    return `${base} · ${data.avg_rpe.toFixed(1)}`;
  return base;
}

/** The adaptation "PR" header — rationale, trigger chip, magnitude summary (§8.3 item 1). */
export function AdaptationHeader({
  adaptation,
}: {
  adaptation: AdaptationOut;
}) {
  const magnitude = summarizeAdaptationMagnitude(adaptation.diff_json ?? []);

  return (
    <div
      data-testid="adaptation-header"
      className="flex flex-col gap-3 rounded-lg border p-4"
      style={{ borderColor: "var(--border)", background: "var(--surface)" }}
    >
      <div className="flex flex-wrap items-center gap-2">
        <span
          className="rounded px-2 py-0.5 font-mono text-[11px]"
          style={{
            background: "color-mix(in srgb, var(--accent) 15%, transparent)",
            color: "var(--accent)",
          }}
        >
          {triggerChipLabel(adaptation)}
        </span>
        {adaptation.stub && (
          <span
            className="rounded px-2 py-0.5 font-mono text-[11px]"
            title="Generated by the stub LLM — dev/QA only"
            style={{
              background: "color-mix(in srgb, var(--amber) 20%, transparent)",
              color: "var(--amber)",
            }}
          >
            STUB
          </span>
        )}
      </div>

      {adaptation.rationale && (
        <p
          className="font-sans text-[14px] leading-relaxed"
          style={{ color: "var(--text)" }}
        >
          {adaptation.rationale}
        </p>
      )}

      <p
        className="font-mono text-[12px] tabular-nums"
        style={{ color: "var(--muted)" }}
        data-testid="adaptation-magnitude-summary"
      >
        {magnitude.label}
      </p>
    </div>
  );
}
