/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/analytics/load": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Load Model */
    get: operations["load_model_api_v1_analytics_load_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/personal-records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Personal Records */
    get: operations["personal_records_api_v1_analytics_personal_records_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/movement-trend/{movement_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Movement Trend */
    get: operations["movement_trend_api_v1_analytics_movement_trend__movement_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/volume-trend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Volume Trend */
    get: operations["volume_trend_api_v1_analytics_volume_trend_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/readiness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_api_v1_analytics_readiness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Benchmarks */
    get: operations["benchmarks_api_v1_analytics_benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/parse-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Parse Log */
    post: operations["parse_log_api_v1_coach_parse_log_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get History */
    get: operations["get_history_api_v1_coach_history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coach/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat */
    post: operations["chat_api_v1_coach_chat_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations/apple-health/connect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Connect Apple Health
     * @description Generate a bearer token for HAE (dev-only endpoint). Returns plaintext once.
     */
    post: operations["connect_apple_health_api_v1_integrations_apple_health_connect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations/apple-health/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Apple Health Token */
    delete: operations["revoke_apple_health_token_api_v1_integrations_apple_health_token_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Integrations */
    get: operations["list_integrations_api_v1_integrations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations/apple-health/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apple Health Sync
     * @description Accept an HAE payload authenticated by a dev ingest bearer token.
     */
    post: operations["apple_health_sync_api_v1_integrations_apple_health_sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/movements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Movements */
    get: operations["list_movements_api_v1_movements_get"];
    put?: never;
    /** Create Movement Route */
    post: operations["create_movement_route_api_v1_movements_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workouts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Workouts Route */
    get: operations["list_workouts_route_api_v1_workouts_get"];
    put?: never;
    /** Create Workout Route */
    post: operations["create_workout_route_api_v1_workouts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workouts/{workout_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Workout Route */
    get: operations["get_workout_route_api_v1_workouts__workout_id__get"];
    put?: never;
    post?: never;
    /** Delete Workout Route */
    delete: operations["delete_workout_route_api_v1_workouts__workout_id__delete"];
    options?: never;
    head?: never;
    /** Patch Workout Route */
    patch: operations["patch_workout_route_api_v1_workouts__workout_id__patch"];
    trace?: never;
  };
  "/api/v1/workouts/{workout_id}/team-session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Workout Team Session Route */
    get: operations["get_workout_team_session_route_api_v1_workouts__workout_id__team_session_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Plans */
    get: operations["list_plans_api_v1_plans_get"];
    put?: never;
    /** Create Plan */
    post: operations["create_plan_api_v1_plans_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Task */
    get: operations["get_task_api_v1_plans_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans/{plan_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Plan */
    get: operations["get_plan_api_v1_plans__plan_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans/{plan_id}/today": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Today Session */
    get: operations["today_session_api_v1_plans__plan_id__today_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans/{plan_id}/revise": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revise Plan */
    post: operations["revise_plan_api_v1_plans__plan_id__revise_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans/{plan_id}/adaptations/detect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Detect Plan Adaptations */
    post: operations["detect_plan_adaptations_api_v1_plans__plan_id__adaptations_detect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/plans/{plan_id}/adaptations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Adaptations */
    get: operations["list_adaptations_api_v1_plans__plan_id__adaptations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/adaptations/{adaptation_id}/merge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Merge Adaptation */
    post: operations["merge_adaptation_api_v1_adaptations__adaptation_id__merge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/adaptations/{adaptation_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Adaptation */
    post: operations["reject_adaptation_api_v1_adaptations__adaptation_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/adaptations/{adaptation_id}/adjust": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Adjust Adaptation
     * @description Reject the existing adaptation and propose a revised one in one atomic step.
     */
    post: operations["adjust_adaptation_api_v1_adaptations__adaptation_id__adjust_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/injuries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Injuries */
    get: operations["list_injuries_api_v1_injuries_get"];
    put?: never;
    /** Report Injury */
    post: operations["report_injury_api_v1_injuries_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team-sessions/role-suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Role Suggestions */
    get: operations["role_suggestions_api_v1_team_sessions_role_suggestions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team-sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Team Sessions */
    get: operations["list_team_sessions_api_v1_team_sessions_get"];
    put?: never;
    /** Create Team Session */
    post: operations["create_team_session_api_v1_team_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team-sessions/{team_session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Team Session */
    get: operations["get_team_session_api_v1_team_sessions__team_session_id__get"];
    put?: never;
    post?: never;
    /** Delete Team Session */
    delete: operations["delete_team_session_api_v1_team_sessions__team_session_id__delete"];
    options?: never;
    head?: never;
    /** Patch Team Session */
    patch: operations["patch_team_session_api_v1_team_sessions__team_session_id__patch"];
    trace?: never;
  };
  "/api/v1/team-sessions/{team_session_id}/participants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Participant */
    post: operations["add_participant_api_v1_team_sessions__team_session_id__participants_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/team-sessions/{team_session_id}/participants/{participant_user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Participant */
    delete: operations["remove_participant_api_v1_team_sessions__team_session_id__participants__participant_user_id__delete"];
    options?: never;
    head?: never;
    /** Patch Participant */
    patch: operations["patch_participant_api_v1_team_sessions__team_session_id__participants__participant_user_id__patch"];
    trace?: never;
  };
  "/api/v1/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Notifications */
    get: operations["list_notifications_api_v1_notifications_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/{notification_id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Read */
    post: operations["mark_read_api_v1_notifications__notification_id__read_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/training-partners": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Training Partners */
    get: operations["list_training_partners_api_v1_training_partners_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdaptationOut */
    AdaptationOut: {
      /** Id */
      id: string;
      /** Plan Id */
      plan_id: string;
      /** User Id */
      user_id: string;
      /** Trigger Type */
      trigger_type: string;
      /** Trigger Data */
      trigger_data: {
        [key: string]: unknown;
      };
      /** Status */
      status: string;
      /** Rationale */
      rationale?: string | null;
      /** Rejection Reason */
      rejection_reason?: string | null;
      /** Diff Json */
      diff_json?: unknown;
      /**
       * Stub
       * @default false
       */
      stub: boolean;
      /** Proposed At */
      proposed_at?: string | null;
      /** Merged At */
      merged_at?: string | null;
      /** Rejected At */
      rejected_at?: string | null;
    };
    /** AddParticipantRequest */
    AddParticipantRequest: {
      /** User Id */
      user_id?: string | null;
      /** Workout Id */
      workout_id?: string | null;
      /** Guest Name */
      guest_name?: string | null;
      /** Role */
      role?: string | null;
    };
    /** AdjustAdaptationRequest */
    AdjustAdaptationRequest: {
      /** Feedback */
      feedback: string;
    };
    /** BenchmarkAttempt */
    BenchmarkAttempt: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Result Display */
      result_display: string;
      /** Result Seconds */
      result_seconds: number;
    };
    /** BenchmarkEntry */
    BenchmarkEntry: {
      /** Name */
      name: string;
      /** Attempts */
      attempts: components["schemas"]["BenchmarkAttempt"][];
      /** Pr Display */
      pr_display: string;
      /** Improvement Display */
      improvement_display: string;
    };
    /** BenchmarkResponse */
    BenchmarkResponse: {
      /** Benchmarks */
      benchmarks: components["schemas"]["BenchmarkEntry"][];
    };
    /** ChatRequest */
    ChatRequest: {
      /** Question */
      question: string;
      /** Session Id */
      session_id?: string | null;
    };
    /** ChatResponse */
    ChatResponse: {
      /** Answer */
      answer: string;
      /**
       * Citations
       * @default []
       */
      citations: components["schemas"]["Citation"][];
      /**
       * Stub
       * @default false
       */
      stub: boolean;
      /** Safety Tier */
      safety_tier?: string | null;
    };
    /** Citation */
    Citation: {
      /** Title */
      title: string;
      /** Source Type */
      source_type: string;
      /** Score */
      score: number;
    };
    /** ConnectResponse */
    ConnectResponse: {
      /** Token */
      token: string;
      /** Token Prefix */
      token_prefix: string;
      /** Ingest Url */
      ingest_url: string;
    };
    /** ConnectionStatus */
    ConnectionStatus: {
      /** Provider */
      provider: string;
      /** Sync Status */
      sync_status: string;
      /** Last Synced At */
      last_synced_at: string | null;
    };
    /** CreateMovementRequest */
    CreateMovementRequest: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Base Movement */
      base_movement: string;
      modality: components["schemas"]["Modality"];
      /** Start Position */
      start_position?: string | null;
      /** Catch Position */
      catch_position?: string | null;
      /** Pause Position */
      pause_position?: string | null;
      /** Tempo */
      tempo?: string | null;
      execution_style?: components["schemas"]["ExecutionStyle"] | null;
      movement_pattern?: components["schemas"]["MovementPattern"] | null;
      limb_style?: components["schemas"]["LimbStyle"] | null;
      /** Implement */
      implement?: string | null;
      /** Default Result Types */
      default_result_types?: string[];
    };
    /** CreateParticipantRequest */
    CreateParticipantRequest: {
      /** User Id */
      user_id?: string | null;
      /** Workout Id */
      workout_id?: string | null;
      /** Guest Name */
      guest_name?: string | null;
      /** Role */
      role?: string | null;
    };
    /** CreatePlanRequest */
    CreatePlanRequest: {
      /**
       * Goal
       * @enum {string}
       */
      goal: "general_fitness" | "strength" | "endurance" | "competition_prep";
      /** Title */
      title: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** Weeks */
      weeks: number;
      /**
       * Training Age
       * @enum {string}
       */
      training_age: "beginner" | "intermediate" | "advanced";
    };
    /** CreateResultRequest */
    CreateResultRequest: {
      /** Movement Id */
      movement_id?: string | null;
      result_type: components["schemas"]["ResultType"];
      /** Load Kg */
      load_kg?: number | string | null;
      /** Reps */
      reps?: number | null;
      /** Time S */
      time_s?: number | null;
      /** Distance M */
      distance_m?: number | string | null;
      /** Calories */
      calories?: number | null;
      /** Height Cm */
      height_cm?: number | string | null;
      /** Rounds */
      rounds?: number | null;
      /** Partial Reps */
      partial_reps?: number | null;
      /** Watts */
      watts?: number | null;
      /** Pace S */
      pace_s?: number | null;
      /**
       * Pace Distance M
       * @default 500
       */
      pace_distance_m: number;
      /** Set Index */
      set_index?: number | null;
      /**
       * Order Index
       * @default 0
       */
      order_index: number;
      /**
       * Is Pr
       * @default false
       */
      is_pr: boolean;
      /** Notes */
      notes?: string | null;
      /** Rpe */
      rpe?: number | string | null;
      /** Rpe Target */
      rpe_target?: number | string | null;
      /** Rir */
      rir?: number | null;
      /** Rest S */
      rest_s?: number | null;
      /** Mean Velocity Ms */
      mean_velocity_ms?: number | string | null;
      /** Peak Velocity Ms */
      peak_velocity_ms?: number | string | null;
    };
    /** CreateTeamSessionRequest */
    CreateTeamSessionRequest: {
      /**
       * Performed At
       * Format: date-time
       */
      performed_at: string;
      /** Name */
      name?: string | null;
      /**
       * Team Size
       * @default 2
       */
      team_size: number;
      scoring_type?: components["schemas"]["ScoringType"] | null;
      /** Team Score */
      team_score?: string | null;
      /** Team Score S */
      team_score_s?: number | null;
      /** Team Score Reps */
      team_score_reps?: number | null;
      /** Notes */
      notes?: string | null;
      /** Participants */
      participants?: components["schemas"]["CreateParticipantRequest"][];
    };
    /** CreateWorkoutRequest */
    CreateWorkoutRequest: {
      /**
       * Performed At
       * Format: date-time
       */
      performed_at: string;
      /** Title */
      title?: string | null;
      /** Notes */
      notes?: string | null;
      /** Bodyweight Kg */
      bodyweight_kg?: number | string | null;
      session_type?: components["schemas"]["SessionType"] | null;
      workout_format?: components["schemas"]["WorkoutFormat"] | null;
      /** Time Cap S */
      time_cap_s?: number | null;
      /** Location */
      location?: string | null;
      /** Session Rpe */
      session_rpe?: number | string | null;
      /** Duration S */
      duration_s?: number | null;
      /** Results */
      results?: components["schemas"]["CreateResultRequest"][];
    };
    /** DailyLoadPoint */
    DailyLoadPoint: {
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Load Au */
      load_au: number;
      /** Atl */
      atl: number;
      /** Ctl */
      ctl: number;
      /** Tsb */
      tsb: number;
      /** Acwr */
      acwr: number | null;
    };
    /** DetectTriggersResponse */
    DetectTriggersResponse: {
      /** Plan Id */
      plan_id: string;
      /** Triggers */
      triggers: {
        [key: string]: unknown;
      }[];
      /** Proposed Adaptations */
      proposed_adaptations: components["schemas"]["AdaptationOut"][];
    };
    /** E1RMPoint */
    E1RMPoint: {
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Estimated 1Rm Kg */
      estimated_1rm_kg: number;
      /** Workout Id */
      workout_id: string;
    };
    /**
     * ExecutionStyle
     * @enum {string}
     */
    ExecutionStyle:
      | "strict"
      | "kipping"
      | "butterfly"
      | "touch_and_go"
      | "dead_stop"
      | "rebound";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /** HistoryMessage */
    HistoryMessage: {
      /** Role */
      role: string;
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** InjuryOut */
    InjuryOut: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Body Region */
      body_region: string;
      /** Pain Level */
      pain_level: number;
      /** Mechanism */
      mechanism?: string | null;
      /** Notes */
      notes?: string | null;
      /** Active */
      active: boolean;
      /** Requires Referral */
      requires_referral: boolean;
      /**
       * Substitutions
       * @default []
       */
      substitutions: string[];
      /**
       * Contraindicated
       * @default []
       */
      contraindicated: string[];
      /** Reported At */
      reported_at?: string | null;
      /** Resolved At */
      resolved_at?: string | null;
    };
    /**
     * LimbStyle
     * @enum {string}
     */
    LimbStyle: "bilateral" | "unilateral" | "alternating";
    /** LoadModelResponse */
    LoadModelResponse: {
      /** Series */
      series: components["schemas"]["DailyLoadPoint"][];
      /** Acwr Now */
      acwr_now: number | null;
      /** Ctl Now */
      ctl_now: number;
      /** Atl Now */
      atl_now: number;
      /** Tsb Now */
      tsb_now: number;
      /** Acwr Zone */
      acwr_zone: string;
    };
    /** MeResponse */
    MeResponse: {
      /** User Id */
      user_id: string;
    };
    /** MesocycleOut */
    MesocycleOut: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Phase */
      phase: string;
      /** Week Start */
      week_start: number;
      /** Week End */
      week_end: number;
      /** Focus */
      focus: string | null;
    };
    /**
     * Modality
     * @enum {string}
     */
    Modality:
      | "strength"
      | "weightlifting"
      | "gymnastics"
      | "mono_structural"
      | "plyometric"
      | "carry"
      | "strongman";
    /** Movement */
    Movement: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Base Movement */
      base_movement: string;
      modality: components["schemas"]["Modality"];
      /** Start Position */
      start_position: string | null;
      /** Catch Position */
      catch_position: string | null;
      /** Pause Position */
      pause_position: string | null;
      /** Tempo */
      tempo: string | null;
      execution_style: components["schemas"]["ExecutionStyle"] | null;
      movement_pattern: components["schemas"]["MovementPattern"] | null;
      limb_style: components["schemas"]["LimbStyle"] | null;
      /** Implement */
      implement: string | null;
      /** Default Result Types */
      default_result_types: string[];
      /** Is Official */
      is_official: boolean;
      /** Created By */
      created_by: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * MovementPattern
     * @enum {string}
     */
    MovementPattern:
      | "squat"
      | "hinge"
      | "push_horizontal"
      | "push_vertical"
      | "pull_horizontal"
      | "pull_vertical"
      | "carry"
      | "rotation"
      | "locomotion";
    /** MovementResult */
    MovementResult: {
      /** Movement Name */
      movement_name: string;
      /**
       * Result Type
       * @enum {string}
       */
      result_type:
        | "reps"
        | "time_s"
        | "distance_m"
        | "weight_kg"
        | "rounds"
        | "calories";
      /** Reps */
      reps?: number | null;
      /** Load Kg */
      load_kg?: number | null;
      /** Time S */
      time_s?: number | null;
      /**
       * Scaled
       * @default false
       */
      scaled: boolean;
      /** Notes */
      notes?: string | null;
    };
    /** Notification */
    Notification: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      type: components["schemas"]["NotificationType"];
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Read At */
      read_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * NotificationType
     * @enum {string}
     */
    NotificationType:
      | "team_session_linked"
      | "team_session_updated"
      | "workout_link_pending";
    /** ParseLogRequest */
    ParseLogRequest: {
      /** Text */
      text: string;
    };
    /** ParseLogResponse */
    ParseLogResponse: {
      parsed: components["schemas"]["ParsedLogEntry"];
      /** Confidence */
      confidence: number;
      /**
       * Stub
       * @default false
       */
      stub: boolean;
    };
    /** ParsedLogEntry */
    ParsedLogEntry: {
      /** Title */
      title?: string | null;
      /**
       * Session Type
       * @enum {string}
       */
      session_type:
        | "metcon"
        | "strength"
        | "skill"
        | "cardio"
        | "mixed"
        | "rest"
        | "unknown";
      /** Workout Format */
      workout_format?:
        | (
            | "amrap"
            | "for_time"
            | "emom"
            | "tabata"
            | "rft"
            | "straight_sets"
            | "other"
          )
        | null;
      /** Duration S */
      duration_s?: number | null;
      /** Session Rpe */
      session_rpe?: number | null;
      /**
       * Results
       * @default []
       */
      results: components["schemas"]["MovementResult"][];
      /**
       * Parsing Notes
       * @default
       */
      parsing_notes: string;
    };
    /** PatchParticipantRequest */
    PatchParticipantRequest: {
      /** Workout Id */
      workout_id?: string | null;
      /** Role */
      role?: string | null;
    };
    /** PatchTeamSessionRequest */
    PatchTeamSessionRequest: {
      /** Name */
      name?: string | null;
      scoring_type?: components["schemas"]["ScoringType"] | null;
      /** Team Score */
      team_score?: string | null;
      /** Team Score S */
      team_score_s?: number | null;
      /** Team Score Reps */
      team_score_reps?: number | null;
      /** Notes */
      notes?: string | null;
      status?: components["schemas"]["TeamSessionStatus"] | null;
    };
    /** PatchWorkoutRequest */
    PatchWorkoutRequest: {
      /** Performed At */
      performed_at?: string | null;
      /** Title */
      title?: string | null;
      /** Notes */
      notes?: string | null;
      /** Bodyweight Kg */
      bodyweight_kg?: number | string | null;
      session_type?: components["schemas"]["SessionType"] | null;
      workout_format?: components["schemas"]["WorkoutFormat"] | null;
      /** Time Cap S */
      time_cap_s?: number | null;
      /** Location */
      location?: string | null;
      /** Session Rpe */
      session_rpe?: number | string | null;
      /** Duration S */
      duration_s?: number | null;
    };
    /** PersonalRecord */
    PersonalRecord: {
      /** Movement Id */
      movement_id: string;
      /** Movement Name */
      movement_name: string;
      /** Best 1Rm Kg */
      best_1rm_kg: number;
      /**
       * Achieved At
       * Format: date
       */
      achieved_at: string;
      /** Workout Id */
      workout_id: string;
    };
    /** PlanDetail */
    PlanDetail: {
      /** Id */
      id: string;
      /** Goal */
      goal: string;
      /** Title */
      title: string;
      /** Branch Name */
      branch_name: string;
      /** Weeks */
      weeks: number;
      /** Status */
      status: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /** Training Age */
      training_age: string | null;
      /** Created At */
      created_at: string;
      /** Mesocycles */
      mesocycles: components["schemas"]["MesocycleOut"][];
      /** Sessions */
      sessions: components["schemas"]["PlannedSessionOut"][];
    };
    /** PlanRevisionRequest */
    PlanRevisionRequest: {
      /** Feedback */
      feedback: string;
    };
    /** PlanSummary */
    PlanSummary: {
      /** Id */
      id: string;
      /** Goal */
      goal: string;
      /** Title */
      title: string;
      /** Branch Name */
      branch_name: string;
      /** Weeks */
      weeks: number;
      /** Status */
      status: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /** Created At */
      created_at: string;
    };
    /** PlanTaskResponse */
    PlanTaskResponse: {
      /** Task Id */
      task_id: string;
      /** Status */
      status: string;
      /** Plan Id */
      plan_id?: string | null;
      /** Error */
      error?: string | null;
    };
    /** PlannedItemOut */
    PlannedItemOut: {
      /** Id */
      id: string;
      /** Movement Name */
      movement_name: string;
      /** Sets */
      sets: number | null;
      /** Reps */
      reps: string | null;
      /** Load Pct 1Rm */
      load_pct_1rm: number | null;
      /** Load Kg */
      load_kg: number | null;
      /** Notes */
      notes: string | null;
      /** Item Order */
      item_order: number;
    };
    /** PlannedSessionOut */
    PlannedSessionOut: {
      /** Id */
      id: string;
      /** Mesocycle Id */
      mesocycle_id: string;
      /**
       * Scheduled Date
       * Format: date
       */
      scheduled_date: string;
      /** Session Type */
      session_type: string;
      /** Title */
      title: string;
      /** Notes */
      notes: string | null;
      /** Status */
      status: string;
      /**
       * Items
       * @default []
       */
      items: components["schemas"]["PlannedItemOut"][];
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Score */
      score: number;
      /** Label */
      label: string;
      /** Acwr */
      acwr: number | null;
      /** Tsb */
      tsb: number;
      /** Mood Avg */
      mood_avg: number | null;
      /** Energy Avg */
      energy_avg: number | null;
      /** Sleep Avg */
      sleep_avg: number | null;
      /** Factors Available */
      factors_available: number;
      /** Recovery Score */
      recovery_score?: number | null;
      /** Coverage */
      coverage?: number | null;
      /** Confidence Tier */
      confidence_tier?: string | null;
      /** Hrv Type */
      hrv_type?: string | null;
    };
    /** RejectAdaptationRequest */
    RejectAdaptationRequest: {
      /** Rejection Reason */
      rejection_reason?: string | null;
    };
    /** ReportInjuryRequest */
    ReportInjuryRequest: {
      /**
       * Body Region
       * @enum {string}
       */
      body_region:
        | "shoulder"
        | "knee"
        | "hip"
        | "lower_back"
        | "wrist"
        | "elbow"
        | "ankle"
        | "neck"
        | "other";
      /** Pain Level */
      pain_level: number;
      /** Mechanism */
      mechanism?: ("overuse" | "acute" | "unknown") | null;
      /** Notes */
      notes?: string | null;
    };
    /** Result */
    Result: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Workout Id
       * Format: uuid
       */
      workout_id: string;
      /** Movement Id */
      movement_id: string | null;
      /** Movement Name */
      movement_name?: string | null;
      result_type: components["schemas"]["ResultType"];
      /** Load Kg */
      load_kg: string | null;
      /** Reps */
      reps: number | null;
      /** Time S */
      time_s: number | null;
      /** Distance M */
      distance_m: string | null;
      /** Calories */
      calories: number | null;
      /** Height Cm */
      height_cm: string | null;
      /** Rounds */
      rounds: number | null;
      /** Partial Reps */
      partial_reps: number | null;
      /** Watts */
      watts: number | null;
      /** Pace S */
      pace_s: number | null;
      /** Pace Distance M */
      pace_distance_m: number;
      /** Set Index */
      set_index: number | null;
      /** Order Index */
      order_index: number;
      /** Is Pr */
      is_pr: boolean;
      /** Notes */
      notes: string | null;
      /** Rpe */
      rpe: string | null;
      /** Rpe Target */
      rpe_target: string | null;
      /** Rir */
      rir: number | null;
      /** Rest S */
      rest_s: number | null;
      /** Mean Velocity Ms */
      mean_velocity_ms: string | null;
      /** Peak Velocity Ms */
      peak_velocity_ms: string | null;
      /** Estimated 1Rm Kg */
      estimated_1rm_kg: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ResultType
     * @enum {string}
     */
    ResultType:
      | "weight"
      | "reps"
      | "time"
      | "distance"
      | "calories"
      | "height"
      | "rounds_reps"
      | "watts"
      | "pace";
    /** RoleSuggestionsResponse */
    RoleSuggestionsResponse: {
      /** Suggestions */
      suggestions: string[];
    };
    /**
     * ScoringType
     * @enum {string}
     */
    ScoringType:
      | "for_time"
      | "amrap"
      | "total_reps"
      | "max_load"
      | "relay"
      | "slowest_finisher";
    /**
     * SessionType
     * @enum {string}
     */
    SessionType:
      | "strength"
      | "metcon"
      | "skill"
      | "mixed"
      | "rest"
      | "deload"
      | "active_recovery";
    /** SyncResponse */
    SyncResponse: {
      /** Rows Inserted */
      rows_inserted: number;
      /** Recovery Computed */
      recovery_computed: boolean;
    };
    /** TeamSession */
    TeamSession: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Name */
      name: string | null;
      /** Team Size */
      team_size: number;
      scoring_type: components["schemas"]["ScoringType"] | null;
      /** Team Score */
      team_score: string | null;
      /** Team Score S */
      team_score_s: number | null;
      /** Team Score Reps */
      team_score_reps: number | null;
      status: components["schemas"]["TeamSessionStatus"];
      /**
       * Performed At
       * Format: date-time
       */
      performed_at: string;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Participants */
      participants?: components["schemas"]["TeamSessionParticipant"][];
    };
    /** TeamSessionListResponse */
    TeamSessionListResponse: {
      /** Items */
      items: components["schemas"]["TeamSessionSummary"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** TeamSessionParticipant */
    TeamSessionParticipant: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Team Session Id
       * Format: uuid
       */
      team_session_id: string;
      /** User Id */
      user_id: string | null;
      /** Workout Id */
      workout_id: string | null;
      /** Guest Name */
      guest_name: string | null;
      /** Role */
      role: string | null;
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
    };
    /**
     * TeamSessionStatus
     * @enum {string}
     */
    TeamSessionStatus: "active" | "completed";
    /** TeamSessionSummary */
    TeamSessionSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Name */
      name: string | null;
      /** Team Size */
      team_size: number;
      scoring_type: components["schemas"]["ScoringType"] | null;
      /** Team Score */
      team_score: string | null;
      /** Team Score S */
      team_score_s: number | null;
      /** Team Score Reps */
      team_score_reps: number | null;
      status: components["schemas"]["TeamSessionStatus"];
      /**
       * Performed At
       * Format: date-time
       */
      performed_at: string;
      /** Participant Count */
      participant_count: number;
    };
    /** TrainingPartner */
    TrainingPartner: {
      /** User Id */
      user_id: string | null;
      /** Guest Name */
      guest_name: string | null;
      /** Display Name */
      display_name: string;
      /** Session Count */
      session_count: number;
      /** Most Common Format */
      most_common_format: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VolumeTrendResponse */
    VolumeTrendResponse: {
      /** Weeks */
      weeks: components["schemas"]["WeeklyVolume"][];
    };
    /** WeeklyVolume */
    WeeklyVolume: {
      /**
       * Week Start
       * Format: date
       */
      week_start: string;
      /** Session Type */
      session_type: string | null;
      /** Total Load */
      total_load: number;
      /** Workout Count */
      workout_count: number;
    };
    /** Workout */
    Workout: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Performed At
       * Format: date-time
       */
      performed_at: string;
      /** Title */
      title: string | null;
      /** Short Hash */
      short_hash: string;
      /** Notes */
      notes: string | null;
      /** Bodyweight Kg */
      bodyweight_kg: string | null;
      session_type: components["schemas"]["SessionType"] | null;
      workout_format: components["schemas"]["WorkoutFormat"] | null;
      /** Time Cap S */
      time_cap_s: number | null;
      /** Location */
      location: string | null;
      /** Session Rpe */
      session_rpe: string | null;
      /** Duration S */
      duration_s: number | null;
      /** Perceived Load Au */
      perceived_load_au: number | null;
      /** Volume Load Kg */
      volume_load_kg: string | null;
      /** Avg Hr */
      avg_hr: number | null;
      /** Max Hr */
      max_hr: number | null;
      /** Trimp Au */
      trimp_au: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Results */
      results?: components["schemas"]["Result"][];
    };
    /**
     * WorkoutFormat
     * @enum {string}
     */
    WorkoutFormat:
      | "strength"
      | "amrap"
      | "emom"
      | "for_time"
      | "tabata"
      | "intervals"
      | "chipper"
      | "benchmark"
      | "open"
      | "partner"
      | "team";
    /** WorkoutListResponse */
    WorkoutListResponse: {
      /** Items */
      items: components["schemas"]["WorkoutSummary"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** WorkoutSummary */
    WorkoutSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Performed At
       * Format: date-time
       */
      performed_at: string;
      /** Title */
      title: string | null;
      /** Short Hash */
      short_hash: string;
      /** Notes */
      notes: string | null;
      /** Bodyweight Kg */
      bodyweight_kg: string | null;
      session_type: components["schemas"]["SessionType"] | null;
      workout_format: components["schemas"]["WorkoutFormat"] | null;
      /** Time Cap S */
      time_cap_s: number | null;
      /** Location */
      location: string | null;
      /** Session Rpe */
      session_rpe: string | null;
      /** Duration S */
      duration_s: number | null;
      /** Perceived Load Au */
      perceived_load_au: number | null;
      /** Volume Load Kg */
      volume_load_kg: string | null;
      /** Avg Hr */
      avg_hr: number | null;
      /** Max Hr */
      max_hr: number | null;
      /** Trimp Au */
      trimp_au: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Result Count
       * @default 0
       */
      result_count: number;
      /**
       * Has Pr
       * @default false
       */
      has_pr: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  load_model_api_v1_analytics_load_get: {
    parameters: {
      query?: {
        days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoadModelResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  personal_records_api_v1_analytics_personal_records_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalRecord"][];
        };
      };
    };
  };
  movement_trend_api_v1_analytics_movement_trend__movement_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        movement_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["E1RMPoint"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  volume_trend_api_v1_analytics_volume_trend_get: {
    parameters: {
      query?: {
        weeks?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VolumeTrendResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  readiness_api_v1_analytics_readiness_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  benchmarks_api_v1_analytics_benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BenchmarkResponse"];
        };
      };
    };
  };
  parse_log_api_v1_coach_parse_log_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParseLogRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ParseLogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_history_api_v1_coach_history_get: {
    parameters: {
      query: {
        session_id: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HistoryMessage"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_api_v1_coach_chat_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  connect_apple_health_api_v1_integrations_apple_health_connect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectResponse"];
        };
      };
    };
  };
  revoke_apple_health_token_api_v1_integrations_apple_health_token_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_integrations_api_v1_integrations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionStatus"][];
        };
      };
    };
  };
  apple_health_sync_api_v1_integrations_apple_health_sync_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncResponse"];
        };
      };
    };
  };
  list_movements_api_v1_movements_get: {
    parameters: {
      query?: {
        query?: string | null;
        modality?: components["schemas"]["Modality"] | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Movement"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_movement_route_api_v1_movements_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMovementRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Movement"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_workouts_route_api_v1_workouts_get: {
    parameters: {
      query?: {
        before_id?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_workout_route_api_v1_workouts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkoutRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workout"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_workout_route_api_v1_workouts__workout_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workout"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_workout_route_api_v1_workouts__workout_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_workout_route_api_v1_workouts__workout_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchWorkoutRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workout"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_workout_team_session_route_api_v1_workouts__workout_id__team_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_plans_api_v1_plans_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanSummary"][];
        };
      };
    };
  };
  create_plan_api_v1_plans_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePlanRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanTaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_api_v1_plans_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanTaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_plan_api_v1_plans__plan_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  today_session_api_v1_plans__plan_id__today_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlannedSessionOut"] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revise_plan_api_v1_plans__plan_id__revise_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanRevisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detect_plan_adaptations_api_v1_plans__plan_id__adaptations_detect_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectTriggersResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_adaptations_api_v1_plans__plan_id__adaptations_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdaptationOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  merge_adaptation_api_v1_adaptations__adaptation_id__merge_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adaptation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdaptationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_adaptation_api_v1_adaptations__adaptation_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adaptation_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json":
          | components["schemas"]["RejectAdaptationRequest"]
          | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdaptationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  adjust_adaptation_api_v1_adaptations__adaptation_id__adjust_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        adaptation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdjustAdaptationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdaptationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_injuries_api_v1_injuries_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InjuryOut"][];
        };
      };
    };
  };
  report_injury_api_v1_injuries_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportInjuryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InjuryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  role_suggestions_api_v1_team_sessions_role_suggestions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoleSuggestionsResponse"];
        };
      };
    };
  };
  list_team_sessions_api_v1_team_sessions_get: {
    parameters: {
      query?: {
        before_id?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSessionListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_team_session_api_v1_team_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTeamSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_team_session_api_v1_team_sessions__team_session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_team_session_api_v1_team_sessions__team_session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_team_session_api_v1_team_sessions__team_session_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchTeamSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_participant_api_v1_team_sessions__team_session_id__participants_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddParticipantRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_participant_api_v1_team_sessions__team_session_id__participants__participant_user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_session_id: string;
        participant_user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_participant_api_v1_team_sessions__team_session_id__participants__participant_user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        team_session_id: string;
        participant_user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchParticipantRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamSession"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_notifications_api_v1_notifications_get: {
    parameters: {
      query?: {
        include_read?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Notification"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_read_api_v1_notifications__notification_id__read_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notification_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Notification"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_training_partners_api_v1_training_partners_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrainingPartner"][];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  me_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
}
